language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
  - '10'
before_install:
  - npm install -g codeclimate-test-reporter
install:
  - npm i .
script:
  - npm run cover
after_success:
  - npm run export
  - codeclimate-test-reporter < coverage/lcov.info
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
